import { Module, ValidationPipe } from '@nestjs/common'
import { GraphQLModule } from '@nestjs/graphql'
import { MercuriusDriver, MercuriusDriverConfig } from '@nestjs/mercurius'
import { ScheduleModule } from '@nestjs/schedule'
import * as path from 'path'
import { UserModule } from '../user/user.module'
import { APP_PIPE } from '@nestjs/core'
import { CountryModule } from '../country/country.module'
import { LeagueModule } from '../league/league.module'
import { TeamModule } from '../team/team.module'
import { MatchModule } from '../match/match.module'

const validationProvider = {
    provide: APP_PIPE,
    useValue: new ValidationPipe(),
}

@Module({
    imports: [
        ScheduleModule.forRoot(),
        GraphQLModule.forRoot<MercuriusDriverConfig>({
            driver: MercuriusDriver,
            graphiql: true,
            autoSchemaFile: path.join(__dirname, './autogenerated-schema.gql'),
        }),
        UserModule,
        CountryModule,
        LeagueModule,
        TeamModule,
        MatchModule,
    ],
    controllers: [],
    providers: [validationProvider],
})
export class AppModule {}
